In [22]:
# Import dependencies
import pandas as pd
import numpy as np
import matplotlib
import re

In [44]:
# Read in data jobs csv files
al = pd.read_csv("Indeed_job_results_Analytics_2019-01-09.csv")
bi = pd.read_csv("Indeed_job_results_Business_Intelligence_Analyst_2019-01-09.csv")
da = pd.read_csv("Indeed_job_results_Data_Analyst_2019-01-09.csv")
de = pd.read_csv("Indeed_job_results_Data_Engineer_2019-01-09.csv")
ds = pd.read_csv("Indeed_job_results_Data_Scientist_2019-01-09.csv")
st = pd.read_csv("Indeed_job_results_Statistician_2019-01-09.csv")

# Concatenate data job files into a single dataframe
data_jobs = pd.concat([al, bi, da, de, ds, st])

# Create a column for job categories and iterate through dataset to categorize each job title

data_jobs["Job Category"] = ""
for i, row in data_jobs.iterrows():
    if re.search("Analytics", row["Title"].title()) or re.search("Analytic", row["Title"].title()):
        row["Job Category"] = "Analytics"
    elif re.search("Data", row["Title"].title()) and re.search("Analyst", row["Title"].title()):
        row["Job Category"] = "Data Analyst"
    elif re.search("Data", row["Title"].title()) and re.search("Scientist", row["Title"].title()):
        row["Job Category"] = "Data Scientist"
    elif re.search("Data", row["Title"].title()) and re.search("Engineer", row["Title"].title()):
        row["Job Category"] = "Data Engineer"
    elif re.search("Business", row["Title"].title()) and re.search("Intelligence", row["Title"].title()):   
        row["Job Category"] = "Business Intelligence Analyst"
    elif re.search("Intern", row["Title"].title()) or re.search("Internship", row["Title"].title()):
        row["Job Category"] = "Internship"
    elif re.search("Business", row["Title"].title()) and re.search("Analyst", row["Title"].title()):   
        row["Job Category"] = "Business Analyst"
    elif re.search("Developer", row["Title"].title()):   
        row["Job Category"] = "Developer"
    elif "Statistician" in row["Title"].title():
        row["Job Category"] = "Statistician"
    elif re.search("Manager", row["Title"].title()) or \
    re.search("Director", row["Title"].title()) or \
    re.search("Dir", row["Title"].title()) or \
    re.search("Lead", row["Title"].title()) or \
    re.search("Head", row["Title"].title()):
        row["Job Category"] = "Management"
    elif re.search("Research", row["Title"].title()):
        row["Job Category"] = "Research"
    else:
        row["Job Category"] = "Other"

# Pare dataframe down to relevant columns and rename columns

# Split Regions, MSAs, and Locations into cities
data_jobs["City"] = ""
data_jobs["State"] = ""
data_jobs["Location"].value_counts()
data_jobs[["City", "State"]] = data_jobs["Location"].str.split(",", n=1, expand=True)
data_jobs["State"] = data_jobs["State"].str.strip()
data_jobs[["State", "ZIP"]] = data_jobs["State"].str.split(" ", n=1, expand=True)
data_jobs["ZIP"] = data_jobs["ZIP"].str.strip()
data_jobs[["ZIP", "Area"]] = data_jobs["ZIP"].str.split(" ", n=1, expand=True)

# Finalize clean jobs dataframes
# data_jobs

In [45]:
# Read in rent csv file
rent = pd.read_csv("City_MedianRentalPrice_1Bedroom.csv")

# Pare the dataframe down to relevant columns and rename them if necessary
rent_columns = ["RegionName", "State", "Metro", "CountyName", "SizeRank", "2018-11"]
rent = rent[rent_columns]
rent.rename(columns = {"RegionName" : "City", "CountyName" : "County"}, inplace = True)

# Split Metro into city columns
rent["City1"] = ""
rent["City2"] = ""
rent["City3"] = ""
rent[["City1", "City2", "City3"]] = rent["Metro"].str.split("-", n=2, expand = True)

# Finalize clean rent file
# rent

In [58]:
# Read in salary csv file
salary = pd.read_csv("MSA_M2017_dl.csv")

# Pare the dataframe down to relevant columns and rename them if necessary
salary_columns = ["PRIM_STATE", "AREA_NAME", "OCC_TITLE", "TOT_EMP", "EMP_PRSE", "JOBS_1000", "H_MEDIAN", "A_MEDIAN"]
salary = salary[salary_columns]
salary.rename(columns = {"PRIM_STATE" : "State", 
                         "AREA_NAME" : "City", 
                         "OCC_TITLE" : "Occupation", 
                         "TOT_EMP" : "Estimated Total Employment", 
                         "EMP_PRSE" : "Employment Percent RSE",
                         "JOBS_1000" : "Occupation per 1000", 
                         "H_MEDIAN" : "Hourly Median Wage", 
                         "A_MEDIAN" : "Annual Median Salary"}, inplace = True)
salary = salary.loc[salary["Occupation"] == "All Occupations"]
salary["City1"] = ""
salary["City2"] = ""
salary[["City1", "City2"]] = rent["City"].str.split("-", n=2, expand = True)
salary

,PRIM_STATE,AREA,AREA_NAME,OCC_CODE,OCC_TITLE,OCC_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC QUOTIENT,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,AK,11260,"Anchorage, AK",00-0000,All Occupations,total,"173,420",1.3,1000.000,1.00,...,22.76,35.80,50.85,"23,170","30,820","47,340","74,470","105,760",NaN,NaN
1,AK,11260,"Anchorage, AK",11-0000,Management Occupations,major,"9,950",2.5,57.380,1.12,...,48.82,65.62,92.45,"53,570","74,470","101,560","136,490","192,300",NaN,NaN
2,AK,11260,"Anchorage, AK",11-1011,Chief Executives,detailed,390,8.3,2.235,1.52,...,75.68,#,#,"86,480","116,870","157,420",#,#,NaN,NaN
3,AK,11260,"Anchorage, AK",11-1021,General and Operations Managers,detailed,"3,450",3.5,19.882,1.28,...,47.67,68.48,96.69,"52,670","72,230","99,150","142,440","201,120",NaN,NaN
4,AK,11260,"Anchorage, AK",11-2011,Advertising and Promotions Managers,detailed,50,16.1,0.265,1.34,...,38.83,67.56,92.72,"54,600","64,700","80,780","140,520","192,860",NaN,NaN
5,AK,11260,"Anchorage, AK",11-2021,Marketing Managers,detailed,160,15.2,0.924,0.60,...,44.43,59.05,80.66,"59,020","73,880","92,410","122,820","167,780",NaN,NaN
6,AK,11260,"Anchorage, AK",11-2022,Sales Managers,detailed,360,12.2,2.095,0.80,...,50.16,67.87,#,"53,660","70,860","104,340","141,170",#,NaN,NaN
7,AK,11260,"Anchorage, AK",11-2031,Public Relations and Fundraising Managers,detailed,80,14.7,0.488,1.03,...,41.99,59.59,71.24,"58,360","70,710","87,340","123,950","148,190",NaN,NaN
8,AK,11260,"Anchorage, AK",11-3011,Administrative Services Managers,detailed,280,7.0,1.598,0.84,...,42.50,55.99,75.06,"48,010","66,540","88,390","116,470","156,130",NaN,NaN
9,AK,11260,"Anchorage, AK",11-3021,Computer and Information Systems Managers,detailed,220,7.6,1.288,0.50,...,52.35,61.14,72.92,"74,080","90,230","108,890","127,170","151,680",NaN,NaN
10,AK,11260,"Anchorage, AK",11-3031,Financial Managers,detailed,490,6.7,2.822,0.71,...,50.61,65.19,86.84,"64,290","83,660","105,260","135,600","180,630",NaN,NaN
11,AK,11260,"Anchorage, AK",11-3051,Industrial Production Managers,detailed,70,13.9,0.406,0.34,...,37.47,57.49,71.62,"54,120","61,360","77,950","119,590","148,960",NaN,NaN
12,AK,11260,"Anchorage, AK",11-3061,Purchasing Managers,detailed,70,7.0,0.417,0.84,...,53.77,60.53,64.65,"64,100","85,700","111,840","125,890","134,470",NaN,NaN
13,AK,11260,"Anchorage, AK",11-3071,"Transportation, Storage, and Distribution Mana...",detailed,370,5.4,2.126,2.55,...,44.02,53.69,64.19,"65,470","76,560","91,560","111,660","133,520",NaN,NaN
14,AK,11260,"Anchorage, AK",11-3121,Human Resources Managers,detailed,100,6.6,0.570,0.60,...,48.35,65.83,79.26,"67,430","79,180","100,560","136,930","164,860",NaN,NaN
15,AK,11260,"Anchorage, AK",11-3131,Training and Development Managers,detailed,40,11.1,0.243,1.00,...,40.25,48.63,63.54,"57,470","67,010","83,720","101,160","132,160",NaN,NaN
16,AK,11260,"Anchorage, AK",11-9021,Construction Managers,detailed,640,8.8,3.713,2.01,...,55.81,76.84,95.36,"75,170","92,050","116,090","159,830","198,340",NaN,NaN
17,AK,11260,"Anchorage, AK",11-9031,"Education Administrators, Preschool and Childc...",detailed,60,35.4,0.332,0.96,...,28.78,36.61,45.07,"32,920","37,910","59,870","76,160","93,740",NaN,NaN
18,AK,11260,"Anchorage, AK",11-9032,"Education Administrators, Elementary and Secon...",detailed,250,1.2,1.432,0.82,...,*,*,*,"101,430","113,360","123,720","134,040","151,700",True,NaN
19,AK,11260,"Anchorage, AK",11-9033,"Education Administrators, Postsecondary",detailed,100,10.5,0.605,0.61,...,41.02,65.90,83.45,"38,660","68,800","85,310","137,080","173,580",NaN,NaN
20,AK,11260,"Anchorage, AK",11-9039,"Education Administrators, All Other",detailed,60,8.2,0.365,1.44,...,41.87,52.81,65.84,"45,130","53,270","87,100","109,840","136,940",NaN,NaN
21,AK,11260,"Anchorage, AK",11-9041,Architectural and Engineering Managers,detailed,260,10.3,1.525,1.21,...,68.24,93.68,#,"94,730","115,950","141,930","194,860",#,NaN,NaN
22,AK,11260,"Anchorage, AK",11-9051,Food Service Managers,detailed,220,18.8,1.273,0.87,...,29.13,37.03,49.33,"41,030","47,270","60,590","77,020","102,600",NaN,NaN
23,AK,11260,"Anchorage, AK",11-9081,Lodging Managers,detailed,60,14.8,0.324,1.26,...,29.83,40.58,47.96,"41,940","47,560","62,040","84,400","99,760",NaN,NaN
24,AK,11260,"Anchorage, AK",11-9111,Medical and Health Services Managers,detailed,470,12.6,2.718,1.12,...,48.58,76.72,#,"62,050","76,540","101,060","159,580",#,NaN,NaN
25,AK,11260,"Anchorage, AK",11-9121,Natural Sciences Managers,detailed,250,1.6,1.417,3.59,...,50.14,55.99,66.44,"79,180","90,360","104,300","116,450","138,190",NaN,NaN
26,AK,11260,"Anchorage, AK",11-9141,"Property, Real Estate, and Community Associati...",detailed,210,18.0,1.194,0.91,...,24.69,45.05,67.19,"34,590","42,910","51,360","93,710","139,750",NaN,NaN
27,AK,11260,"Anchorage, AK",11-9151,Social and Community Service Managers,detailed,170,9.8,0.998,1.00,...,36.82,46.86,57.58,"43,900","53,730","76,580","97,460","119,770",NaN,NaN
28,AK,11260,"Anchorage, AK",11-9161,Emergency Management Directors,detailed,60,13.3,0.322,4.80,...,32.34,36.97,49.64,"52,350","60,680","67,270","76,890","103,250",NaN,NaN
29,AK,11260,"Anchorage, AK",11-9199,"Managers, All Other",detailed,910,8.2,5.268,1.75,...,52.16,65.24,88.67,"60,660","81,760","108,500","135,700","184,430",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156533,WY,16940,"Cheyenne, WY",49-3042,"Mobile Heavy Equipment Mechanics, Except Engines",detailed,80,19.0,1.874,2.03,...,26.42,29.48,32.46,"42,710","49,570","54,960","61,320","67,520",NaN,NaN
156534,WY,16940,"Cheyenne, WY",49-3093,Tire Repairers and Changers,detailed,60,39.0,1.214,1.51,...,10.63,11.84,15.14,"16,950","19,520","22,120","24,630","31,490",NaN,NaN
156535,WY,16940,"Cheyenne, WY",49-9012,"Control and Valve Installers and Repairers, Ex...",detailed,40,41.4,0.863,2.58,...,21.11,23.69,33.49,"33,740","38,340","43,900","49,260","69,660",NaN,NaN
156536,WY,16940,"Cheyenne, WY",49-9021,"Heating, Air Conditioning, and Refrigeration M...",detailed,100,45.5,2.256,1.05,...,25.37,28.17,29.75,"31,250","42,950","52,770","58,590","61,880",NaN,NaN
156537,WY,16940,"Cheyenne, WY",49-9041,Industrial Machinery Mechanics,detailed,140,18.3,3.059,1.28,...,27.57,29.90,34.41,"37,230","52,230","57,350","62,190","71,560",NaN,NaN
156538,WY,16940,"Cheyenne, WY",49-9051,Electrical Power-Line Installers and Repairers,detailed,60,22.9,1.265,1.55,...,40.63,45.36,48.65,"63,450","71,600","84,520","94,340","101,200",NaN,NaN
156539,WY,16940,"Cheyenne, WY",49-9071,"Maintenance and Repair Workers, General",detailed,400,7.7,8.758,0.92,...,17.94,23.40,28.35,"21,270","26,610","37,310","48,660","58,970",NaN,NaN
156540,WY,16940,"Cheyenne, WY",51-0000,Production Occupations,major,"1,240",10.5,27.392,0.43,...,18.01,28.00,42.76,"21,970","26,970","37,470","58,240","88,950",NaN,NaN
156541,WY,16940,"Cheyenne, WY",51-1011,First-Line Supervisors of Production and Opera...,detailed,110,10.8,2.351,0.55,...,28.60,38.01,59.27,"36,600","45,020","59,480","79,070","123,280",NaN,NaN
156542,WY,16940,"Cheyenne, WY",51-2041,Structural Metal Fabricators and Fitters,detailed,**,**,**,**,...,14.13,16.01,18.58,"22,620","25,960","29,390","33,290","38,650",NaN,NaN
156543,WY,16940,"Cheyenne, WY",51-2098,"Assemblers and Fabricators, All Other, Includi...",detailed,100,19.1,2.156,0.24,...,13.30,14.39,15.84,"22,930","25,490","27,670","29,930","32,940",NaN,NaN
156544,WY,16940,"Cheyenne, WY",51-3011,Bakers,detailed,50,22.7,1.051,0.82,...,11.16,13.47,17.97,"18,710","20,620","23,210","28,010","37,370",NaN,NaN
156545,WY,16940,"Cheyenne, WY",51-4041,Machinists,detailed,30,10.3,0.671,0.25,...,15.83,18.45,26.30,"26,890","28,940","32,920","38,390","54,690",NaN,NaN
156546,WY,16940,"Cheyenne, WY",51-4121,"Welders, Cutters, Solderers, and Brazers",detailed,140,27.9,3.077,1.16,...,*,*,*,*,*,*,*,*,NaN,NaN
156547,WY,16940,"Cheyenne, WY",51-6011,Laundry and Dry-Cleaning Workers,detailed,90,16.0,1.880,1.28,...,11.15,13.06,14.61,"17,550","20,190","23,190","27,160","30,390",NaN,NaN
156548,WY,16940,"Cheyenne, WY",51-9023,"Mixing and Blending Machine Setters, Operators...",detailed,40,11.1,0.870,0.96,...,17.54,19.55,32.55,"25,660","32,340","36,480","40,670","67,690",NaN,NaN
156549,WY,16940,"Cheyenne, WY",51-9061,"Inspectors, Testers, Sorters, Samplers, and We...",detailed,110,19.8,2.331,0.62,...,23.39,30.67,40.68,"36,150","41,850","48,650","63,790","84,620",NaN,NaN
156550,WY,16940,"Cheyenne, WY",51-9198,Helpers--Production Workers,detailed,**,**,**,**,...,14.03,17.01,19.92,"20,960","23,910","29,180","35,380","41,440",NaN,NaN
156551,WY,16940,"Cheyenne, WY",53-0000,Transportation and Material Moving Occupations,major,"4,020",4.8,88.685,1.27,...,15.81,21.00,28.90,"21,640","26,520","32,880","43,680","60,110",NaN,NaN
156552,WY,16940,"Cheyenne, WY",53-1048,First-Line Supervisors of Transportation and M...,detailed,230,11.7,5.131,1.85,...,25.17,29.43,35.69,"34,770","41,810","52,360","61,210","74,240",NaN,NaN
156553,WY,16940,"Cheyenne, WY",53-3022,"Bus Drivers, School or Special Client",detailed,160,1.2,3.425,0.96,...,17.41,18.59,19.29,"32,300","33,770","36,220","38,660","40,130",NaN,NaN
156554,WY,16940,"Cheyenne, WY",53-3031,Driver/Sales Workers,detailed,490,18.8,10.892,3.64,...,13.46,14.64,18.89,"20,680","25,420","28,000","30,460","39,290",NaN,NaN
156555,WY,16940,"Cheyenne, WY",53-3032,Heavy and Tractor-Trailer Truck Drivers,detailed,890,9.0,19.577,1.60,...,21.61,27.88,33.52,"23,190","34,200","44,950","58,000","69,720",NaN,NaN
156556,WY,16940,"Cheyenne, WY",53-3033,Light Truck or Delivery Services Drivers,detailed,170,11.9,3.834,0.62,...,12.69,16.69,19.36,"18,630","22,050","26,390","34,720","40,260",NaN,NaN
156557,WY,16940,"Cheyenne, WY",53-3041,Taxi Drivers and Chauffeurs,detailed,**,**,**,**,...,9.51,11.87,18.96,"16,750","17,870","19,770","24,690","39,440",NaN,NaN
156558,WY,16940,"Cheyenne, WY",53-3099,"Motor Vehicle Operators, All Other",detailed,**,**,**,**,...,14.93,21.80,24.42,"17,580","19,920","31,060","45,340","50,790",NaN,NaN
156559,WY,16940,"Cheyenne, WY",53-6031,Automotive and Watercraft Service Attendants,detailed,70,19.2,1.461,1.75,...,12.94,14.37,16.76,"21,420","23,890","26,920","29,880","34,850",NaN,NaN
156560,WY,16940,"Cheyenne, WY",53-7061,Cleaners of Vehicles and Equipment,detailed,80,16.6,1.803,0.69,...,11.35,12.92,14.65,"18,960","21,050","23,620","26,860","30,470",NaN,NaN
156561,WY,16940,"Cheyenne, WY",53-7062,"Laborers and Freight, Stock, and Material Move...",detailed,580,19.8,12.702,0.67,...,13.52,15.57,18.58,"20,770","24,120","28,130","32,390","38,640",NaN,NaN
156562,WY,16940,"Cheyenne, WY",53-7081,Refuse and Recyclable Material Collectors,detailed,50,37.8,1.002,1.24,...,13.80,14.82,15.44,"23,460","26,560","28,690","30,830","32,110",NaN,NaN

In [ ]:
# Read in crime csv file